---
platform: linux

image_resource:
  type: docker-image

inputs:
- name: pxf_src
- name: gpdb_package

outputs:
- name: dist

params:
  TARGET_OS:

run:
  path: pxf_src/concourse/scripts/build.bash
